### ISSUE TITLE
Change librtlsdr reference?

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dabtools#10]
It has just been pointed out to me that librtlsdr is actively maintained. Although everyone looks to the OsMoCom website and repository, or even the https://github.com/steve-m/librtlsdr mirror of it, these have been unchanged for a long while. Is seems though there is https://github.com/librtlsdr/librtlsdr which is actively maintained and releasing regularly.

I intend to post bug reports to Debian and Fedora asking them to switch from the OsMoCom repository to this one, and to update their packages.

We should make a decision what to say in our README.

PS the link in our README is wrong anyway so a change of some sort is necessary.

**Comment by mpbraendli** [comment]
This seems to be mostly "not our problem" if it has to be fixed in the repositories. IMHO you can close this issue once you fixed the README.

**Comment by mpbraendli** [comment]
Or switch to soapysdr which would enable dabtools to use many more devices than just the rtlsdr.

**Comment by russel** [comment]
Hummm… I hadn't even thought of that route, I had thought it was /dev/swradioX or rtlsdr, but then for my hardware it is (I guess I should get an AirSpy Mini). I wonder if soapysdr stand is an analogous position to libdvbv5 for Linux DVB and is therefore very much the right way for application level code to go. I am guessing we are rapidly discussing our way to a dab2eti rewrite from scratch.

**Comment by basicmaster** [comment]
Switching to an abstraction like soapysdr would be absolutely preferable; I would really like to use an HackRF or AirSpy Mini instead of the deaf RTL stick.

**Comment by russel** [comment]
I suspect then that means C++11, since I can't find any Rust bindings that are not vapourware, and I haven't been able to try DStep on the API to create a D binding. I am assuming we do not want to work in Python.

**Comment by russel** [comment]
Just to note though that whilst Debian packages soapysdr, Fedora does not.

**Comment by mpbraendli** [comment]
I'm also in favour of using SoapySDR. I'm fine with both keeping librtlsdr or replacing it.

**Comment by russel** [comment]
Just to add, this seems like a decision made, which is fine, and that there is a Rust binding for SoapySDR.
