### ISSUE TITLE
dab2eti excute with timer

### ISSUE THREAD

**Issue by YoannQueret** [Opendigitalradio/dabtools#11]
Is it possible to add 2 new parameters to dab2eti :
- first for waiting sync during a maximum time (in sec)
- second for recording ETI stream during a fixed time (in sec) and exit after

Example : ./dab2eti -g 30 -t 300 202928000 > 9a-dump.eti

wainting sync gain for 30 sec and record eti during 300 sec (5 minutes)

**Comment by andimik** [comment]
Well, for your 2nd question there is a tool called timeout. 

`apt-get install timeout
`
`timeout 300 dab2eti [parameters]
`

Should do what you want. But I have not tested it.

**Comment by mpbraendli** [comment]
Hi Yoann,
I know you want to have this so that you can do some measurements. If you happen to do them with etisnoop, its new -n option could solve the second requirement.
