### ISSUE TITLE
Rewrite dab2eti in Go, Rust, C++14?

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dabtools#12]
I wonder if a rewrite of dab2eti using one of Go, Rust, C++14 would enable:

1. a review of the algorithms and how they are implemented; and
2. protection against some of the memory fails that happen from time to time.

There are binding to librtlsdr in Go, Rust and C++14. The Go and Rust ones are manually created but maintained – I have checked with the authors. The C++14 binding is trivially just the library itself.

I would also have suggested D in the candidate list but there is no current binding to librtlsdr, I do not really want to create anything manual, and I am not sure the tool DStep is yet up to the task of making a binding automatically, but I will check further.

Given that dab2eti → dablin_gtk is still not competitive with qt-dab as a dab player, the status quo (even with the recent change of threshholds) is not really a position to stay in. For me switching from C to another language for a total rewrite would create energy to try and achieve the goal of making dab2eti → dablin_gtk as good as qt-dab.

**Comment by mpbraendli** [comment]
The question is what the purpose this project has. Is it a playground for us to try new technologies? Is our aim to create the *best* SDR DAB receiver on the planet for end users? Or maybe one that is easy to use for monitoring and/or industrial applications?

If it's the first, I would love to find an excuse to collaborate on a Rust project. Why Rust? C++14 is too close to the rest I'm doing, and I feel that Go is not different enough. Haskell or Elixir maybe? (ok don't take that too seriously...)

For the second part, I believe this is the aim of SDR-J/qt-dab. Trying to do follow the same goal is not what motivates me. (But maybe it's what motivates you!)

The last goal is the one that would clearly be interesting for some users, and is not really available currently. Then the question of the language is about what platforms we want to support. debian stable (the only distribution we officially support for the mmbTools) doesn't have a rust package, is it easy for our users to get it working there? C++14 might be delicate too, but C++11 would be fine. This could lead to some more interesting DSP work (e.g. measuring channel impulse response, MER and TII come to mind)

Personally, the "measurement and industrial applications receiver" combined with "discover Rust" sounds really nice to my ears.

What's your feeling about these questions?

@basicmaster are you interested in/have time for such an activity?

**Comment by russel** [comment]
There is a Haskell binding for librtlsdr. https://hackage.haskell.org/package/rtlsdr

**Comment by russel** [comment]
Go, C++11, and Rust all allow for creating static executables, which should work on any version of Debian, Fedora, Ubuntu, Mint, Arch, etc. For development, there is a small shell (Bash?) script that allows for downloading and keeping up to date a ready to use Rust system, including Cargo. Go would require (currently at least) downloading an official distribution for each release. Not being packaged is not a barrier for either Go or Rust, but Rust is definitely easier in that sense.

One of my end goals is to write a dabsrc plugin for GStreamer – most likely to go alongside dvbsrc in the Bad Plugins. This would probably have to be written in C – though some of the GStreamer people are muttering about a Rust implemented version of the GStreamer system. Then to port/fork DABlin as a UI over GStreamer to work as a companion UI to Me TV. An interim goal is to have a working Gtk DAB player, but I guess that can be fulfilled with Qt-DAB, at least in the short term. Sadly though the Qt UI doesn't really fit in a GNOME/Gtk context – hence wanting to move DABlin forward.

So really I am "into" the first two of your three proposed goals. This would seem to give us overlap in the "rewrite in Rust" area.

**Comment by basicmaster** [comment]
I have a quite convervative opinion about this and prefer C++11 (which also is due to not having any knowledge of Haskell or Rust). The reason is that one doesn't have to rely on the existance/maintenance of bindings (e.g. consider adding further SDR devices later) and also can exchange code with other existing projects, in both directions. But this is just my opinion. Whatever is decided - as long as it improves the DAB reception, its great.

**Comment by russel** [comment]
I think the Haskell proposal was actually a jest, even though it wouldn't be a bad choice. It seems people here are that that enamoured of the Go idea – even though Go is supposed to be a C replacement. ;-) 

Rust and D are intended as C++ replacements, taking different approaches to that task. Both are already well ahead of C++17 in almost all situations – except the use of C header files as bindings. Having said that I think the Rust bindings are not really a problem, there are three and the three authors are committed to maintaining them. Restricting to C++11 seems annoying for a new code in 2017 – things like std::filesystem and the like missing leading to having to use lots of Boost. (Though I still have to use std::experimental::filesystem just now :-(

**Comment by russel** [comment]
Sorry I seemed to let this drop. I won't really be able to get stuck in again till June, however there is a flurry of activity across projects.

If there are a number of C linkage libraries with no Rust bindings that a rewritten dab2eti would need to access that does rule out Rust unless the idea is also to wrap those libraries. D could still be a player, but it would be easier to use C++. Is there any reason not to go with C++14? (Gtkmm is now C++14 I believe.) C++17 has got a lot of good stuff, and if C++ it would be worth keeping C++17 in mind if not actually using it.

An anecdote: I have had recently to write a program from scratch and I started doing it in simultaneously in Go, Rust and D. The Go code was much quicker to write, D did the same thing in less code, Rust was harder to write, but I did have to learn more along the way, much less code than Go, a bit more than D. Some other issues then stepped in and am progressing this in D. Trying to write this in C++ would have been way harder, but doable.  Go and D are definitely easier than Rust for C and C++ programmers to learn.

Go has LiteIDE and Gogland as IDEs, Rust has an IntelliJ IDEA plugin which works but is clearly a WIP. D has no serious IDE as yet, but I am going to contribute to the IntelliJ IDEA plugin later in the year – it's a Kotlin thing (long story).  C++ has CLion which I find way better than Eclipse. CLion requires CMake (it would be nice if they supported Meson, but they do not). Always there is also VIM and Emacs.

I terms of process, we could either evolve the current code, or start from scratch. The former would clearly add bias towards C++14. The latter would give more freedom of choice.

**Comment by russel** [comment]
Restarting this thread, sorry for the delay.

I am now doing stuff in Rust for GStreamer, I propose to add a DAB source for GStreamer. Much of the code for that will be the same as the code for a dab2eti written in Rust. So going back to @mpbraendli original questions:

1. Rewriting dab2eti in Rust would be a playground to try stuff out.
2. I am interested in a great DAB player for use with USB radio devices on laptops and workstations. Qt_DAB doesn't really work for me, WelleIO is much more what I want. DABlin is more like Qt_DAB.

and then:

3. Creating a DAB source for GStreamer allows for a WelleIO style UI (probably in GTK+ as DABlin is) written in Rust or D.

**Comment by mpbraendli** [comment]
I'd like to keep the master branch functional. Starting a port to Rust in another branch or in a fork is of course fine.
The work in GStreamer probably is best done in a separate repository.

**Comment by russel** [comment]
I was thinking a Rust port of dab2eti should probably happen in a new repository, but a branch in this one works. It is really a question of process: I'd prefer not to go through pull requests until there is something working.

The GStreamer work will happen in a repository gst-plugin-dab, but I haven't uploaded it to GitHub just yet.
