### ISSUE TITLE
Is Wavefinder support still needed?

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dabtools#6]
I wonder if the Wavefinder device support is worth continuing with, or whether it should be dropped.

**Comment by kylegordon** [comment]
As a Wavefinder owner, and hopeful user after I finish unpacking from the house move, I'd be sad to see it dropped.

**Comment by mpbraendli** [comment]
I vote for @kylegordon to become official dabtools wavefinder test expert :-D I'll print business cards if needed!

**Comment by kylegordon** [comment]
Gladly! - goes hunting through boxes - :-)

**Comment by russel** [comment]
OK there is an active user, thus support must remain. Question answered. :-)

Of course this means an adjustment to the current CMake build is required so we can delete the Make build and be consistent with teh ODR implicit policy of having one and only one build system.

**Comment by PartialVolume** [comment]
I also have a wavefinder I would like to get running with this software if possible, unfortunately I'm having trouble building the wavefinder module which I'll document in a separate issue.
